<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8"/>
        <PackageReference Include="DynaJson" Version="2.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\REDox.Dynamic\REDox.Dynamic.csproj"/>
        <ProjectReference Include="..\..\src\REDox\REDox.csproj"/>
        <ProjectReference Include="..\REDox.Benchmarks\REDox.Benchmarks.csproj"/>
    </ItemGroup>

</Project>