<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MessagePack" Version="3.1.10" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\REDox.MessagePack\REDox.MessagePack.csproj" />
        <ProjectReference Include="..\..\src\REDox\REDox.csproj" />
        <ProjectReference Include="..\REDox.Tests\REDox.Tests.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>