<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>REDox.Html</RootNamespace>
        <Title>$(AssemblyName)</Title>
        <Description>Practical HTML structural parser/writer</Description>
        <PackageId>CAPCOM.$(AssemblyName)</PackageId>
        <PackageTags>$(PackageTags);html;parser</PackageTags>
        <Version>$(VersionPrefix)-preview</Version>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\REDox\REDox.csproj" />
    </ItemGroup>
</Project>
