<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>REDox.Ini</RootNamespace>
        <Title>$(AssemblyName)</Title>
        <Description>INI support</Description>
        <PackageId>CAPCOM.$(AssemblyName)</PackageId>
        <PackageTags>$(PackageTags);ini;parser;config</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\REDox\REDox.csproj"/>
    </ItemGroup>
</Project>
