<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8"/>
        <PackageReference Include="Dahomey.Cbor" Version="1.26.3"/>
        <PackageReference Include="PeterO.Cbor" Version="4.5.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\REDox.Cbor\REDox.Cbor.csproj"/>
        <ProjectReference Include="..\..\src\REDox\REDox.csproj"/>
        <ProjectReference Include="..\REDox.Benchmarks\REDox.Benchmarks.csproj"/>
    </ItemGroup>

</Project>